# Generated by Django 4.0.4 on 2022-06-21 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Investido')),
                ('data_entrada', models.DateField(blank=True, default=datetime.date, null=True, verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, default=datetime.date, null=True, verbose_name='Data de Saida')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
