# Generated by Django 4.0.4 on 2022-06-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='proprietario_id',
            field=models.IntegerField(default=0, verbose_name='Proprietario ID'),
        ),
    ]
