# Generated by Django 4.0.4 on 2022-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_investimento_proprietario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='proprietario_id',
            field=models.IntegerField(verbose_name='Proprietario ID'),
        ),
    ]
