# Generated by Django 4.0.4 on 2022-06-21 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_investimento_proprietario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='data_entrada',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='data_saida',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de Saida'),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='valor',
            field=models.IntegerField(verbose_name='Valor Investido'),
        ),
    ]
