# Generated by Django 4.0.4 on 2022-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_investimento_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='valor',
            field=models.FloatField(verbose_name='Valor Investido'),
        ),
    ]
